package com.example.restaurantmenu

import com.example.restaurantmenu.enums.Category
import com.example.restaurantmenu.models.Dish

val dishes = listOf<Dish>(
  Dish(
    R.string.pao_de_alho,
    R.string.pao_de_alho_descricao,
    15.0,
    R.drawable.paodealhocaseiro,
    Category.STARTER,
    10.0
  ),
  Dish(
    R.string.pudim,
    R.string.pudim_descricao,
    7.0,
    R.drawable.pudim,
    Category.DESSERT,
    0.0
  ),
  Dish(
    R.string.banoffee,
    R.string.banoffee_descricao,
    8.0,
    R.drawable.banoffe,
    Category.DESSERT,
    1.0
  ),
  Dish(
    R.string.torta_de_limao,
    R.string.torta_de_limao_descricao,
    6.0,
    R.drawable.tortadelimao,
    Category.DESSERT,
    2.0
  ),
  Dish(
    R.string.agua_mineral,
    R.string.agua_mineral_descricao,
    5.0,
    R.drawable.aguamineral,
    Category.DRINK,
    0.0
  ),
  Dish(
    R.string.bacalhau,
    R.string.bacalhau_descricao,
    70.0,
    R.drawable.bacalhau,
    Category.MAIN,
    30.0
  ),
  Dish(
    R.string.feijoada,
    R.string.feijoada_descricao,
    50.0,
    R.drawable.feijoada,
    Category.MAIN,
    30.0
  ),
  Dish(
    R.string.medalhao,
    R.string.medalhao_descricao,
    60.0,
    R.drawable.medalhao,
    Category.MAIN,
    40.0
  ),
  Dish(
    R.string.pastel_de_camarao,
    R.string.pastel_de_camarao_descricao,
    30.0,
    R.drawable.pasteldecamarao,
    Category.STARTER,
    15.0
  ),
  Dish(
    R.string.pate_de_frango,
    R.string.pate_de_frango_descricao,
    25.0,
    R.drawable.patedefrangocomcenoura,
    Category.STARTER,
    15.0
  ),
  Dish(
    R.string.peixe_frito,
    R.string.peixe_frito_descricao,
    60.0,
    R.drawable.peixefrito,
    Category.MAIN,
    50.0
  ),
  Dish(
    R.string.ratatouille,
    R.string.ratatouille_descricao,
    70.0,
    R.drawable.ratatouille,
    Category.MAIN,
    50.0
  ),
  Dish(
    R.string.refrigerante,
    R.string.refrigerante_descricao,
    10.0,
    R.drawable.refrigerante,
    Category.DRINK,
    1.0
  ),
  Dish(
    R.string.suco_de_laranja,
    R.string.suco_de_laranja_descricao,
    10.0,
    R.drawable.sucodelaranja,
    Category.DRINK,
    5.0
  )
)