package com.example.restaurantmenu

import com.example.restaurantmenu.enums.Category
import com.example.restaurantmenu.models.Dish

val dishes = listOf<Dish>(
  Dish(
    R.string.tartine,
    R.string.tartine_descricao,
    15.0,
    R.drawable.tartine,
    Category.STARTER,
    10.0
  ),
  Dish(
    R.string.coq,
    R.string.coq_descricao,
    70.0,
    R.drawable.coq,
    Category.MAIN,
    30.0
  ),
  Dish(
    R.string.creme_brulee,
    R.string.creme_brulee_descricao,
    7.0,
    R.drawable.creme,
    Category.DESSERT,
    0.0
  ),
  Dish(
    R.string.agua_mineral,
    R.string.agua_mineral_descricao,
    5.0,
    R.drawable.aguamineral,
    Category.DRINK,
    0.0
  ),
  Dish(
    R.string.coquilles,
    R.string.coquilles_descricao,
    8.0,
    R.drawable.coquilles,
    Category.STARTER,
    1.0
  ),
  Dish(
    R.string.salada,
    R.string.salada_descricao,
    6.0,
    R.drawable.salada,
    Category.STARTER,
    2.0
  ),
  Dish(
    R.string.quiche,
    R.string.quiche_descricao,
    50.0,
    R.drawable.quiche,
    Category.STARTER,
    30.0
  ),
  Dish(
    R.string.bouilabaisse,
    R.string.bouilabaisse_descricao,
    60.0,
    R.drawable.bouillabaisse,
    Category.MAIN,
    40.0
  ),
  Dish(
    R.string.cassoulet,
    R.string.cassoulet_descricao,
    30.0,
    R.drawable.cassoulet,
    Category.MAIN,
    15.0
  ),
  Dish(
    R.string.tarte,
    R.string.tarte_descricao,
    25.0,
    R.drawable.tarte,
    Category.DESSERT,
    15.0
  ),
  Dish(
    R.string.macarons,
    R.string.macarons_descricao,
    60.0,
    R.drawable.macarons,
    Category.DESSERT,
    50.0
  ),
  Dish(
    R.string.eclair,
    R.string.eclair_descricao,
    30.0,
    R.drawable.eclair,
    Category.DESSERT,
    20.0
  ),
  Dish(
    R.string.ratatouille,
    R.string.ratatouille_descricao,
    70.0,
    R.drawable.ratatouille,
    Category.MAIN,
    50.0
  ),
  Dish(
    R.string.refrigerante,
    R.string.refrigerante_descricao,
    10.0,
    R.drawable.refrigerante,
    Category.DRINK,
    1.0
  ),
  Dish(
    R.string.suco_de_laranja,
    R.string.suco_de_laranja_descricao,
    10.0,
    R.drawable.sucodelaranja,
    Category.DRINK,
    5.0
  )
)